[package]
name = "procul"
version = "0.1.0"

description = "A minimal terminal Mastodon client"
authors = ["Cory Driscoll <cory@drisc.io>"]

[dependencies]
mammut = "0.12.0"
toml = "0.4.6"
rustyline = "2.0.1"
tui = "0.6.1"
kuchiki = "0.7.3"
webbrowser = "0.2.2"
#ncurses = "5.98.0"